name: Deploy AzMan project to Azure Function App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_RBAC_CREDENTIALS
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'azman-v2'  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: jpda/login@v1.2
      with:
        enable-managed-identity: true
        user-managed-identity-resource-id: '/subscriptions/e7048bdb-835c-440f-9304-aa4171382839/resourceGroups/service-me-p-github-actions-runner/providers/Microsoft.ManagedIdentity/userAssignedIdentities/user-managed-identity-for-test'
   
    - run: |
        az vm list
